apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rhn9j3shk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rhn9j3shk-java-quarkus-gitops